name: release

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 6 * * 1"
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Version
        id: version
        run: |
          echo "::set-output name=VERSION::$(cat VERSION)"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/arm,linux/arm64
          push: true
          tags: niallbyrne/plex-server-docker-rpi:${{ steps.version.outputs.VERSION }},niallbyrne/plex-server-docker-rpi:latest
